require 'active_record'
# require_relative './bin/run.rb'
#
# task :environment do
#   ENV["ACTIVE_RECORD_ENV"] ||= "development"
#   puts ENV["ACTIVE_RECORD_ENV"]
# end
#
task :console => :environment do
  Pry.start
end


include ActiveRecord::Tasks
DatabaseTasks.db_dir = 'db'
DatabaseTasks.migrations_paths = 'db/migrate'
seed_loader = Class.new do
  def load_seed
    load "#{ActiveRecord::Tasks::DatabaseTasks.db_dir}/seeds.rb"
  end
end
DatabaseTasks.seed_loader = seed_loader.new
load 'active_record/railties/databases.rake'

# task :cli => :environment do
#   CLI.new.start
# end
